using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjetoSistema
{
    internal class CadastrarProduto
    {
        public int IdProduto;
        public string Nome;
        public string CodigoInterno;
        public string CodigoAdicional;
        public string CodigoBarras;
        public string UnidadeMedida;
        public string referencia;
        public string Descricao;
        public string TipoProduto;
        public string Categoria;
        public string Subcategoria;
        public string Fabricante;
        public string Fornecedor;
        public string Status;
        public string ReceberDesconto;
        public string VenderFracionado;
        public string ControlarEstoque;
        public string Balanca;
        public string BalancaCheckout;
        public string AtualizarPreco;
        public string AtualizarNcmEntradaEstoque;
        public decimal PrecoCompra;
        public decimal Ipi;
        public decimal ValorFrete;
        public decimal Custo;
        public decimal CustoMedio;
        public decimal PrecoVenda;
        public decimal Preco2;
        public decimal Preco3;
        public decimal Preco4;
        public decimal Margem;
        public decimal Margem2;
        public decimal Margem3;
        public decimal Margem4;
        public decimal QntMinima;
        public decimal QntMinima2;
        public decimal QntMinima3;
        public decimal QntMinima4;
        public decimal DescMax;
        public decimal DescMax2;
        public decimal DescMax3;
        public decimal DescMax4;
        public string GrupoTrib;
        public string Cst;
        public string Cfop;
        public string Origem;
        public string Ncm;
        public string Cest;
        public string Genero;
        public decimal IcmsSaida;
        public decimal ReducaoBaseCalEntrada;
        public string ObsIcms;
        public decimal IcmsEntrada;
        public decimal ReducaoBaseCalSaida;
        public decimal Fcp;
        public string PisSaida;
        public decimal PisAliquotaSaida;
        public string PisEntrada;
        public decimal PisAliquotaEntrada;
        public string ConfinsSaida;
        public decimal ConfinsAliquotaSaida;
        public string ConfinsEntrada;
        public decimal ConfinsAliquotaEntrada;
        public string IpiSaida;
        public decimal IpiAliquotaSaida;
        public string IpiEntrada;
        public decimal IpiAliquotaEntrada;
        public decimal Estoque;
        public decimal QntEmbalagem;
        public decimal EstoqueMaximo;
        public decimal EstoqueMinimo;
        public decimal PesoBruto;
        public decimal PesoLiquido;
        public DateTime DataValidade;
        public decimal Tara;
        public string LocalNoEstabelecimento;
        public string Empresa;
        public string LocalNoEstoque;
        public decimal Saldo;
        public DateTime PromocaoDataInicial;
        public DateTime PromocaoDataFinal;
        public decimal ValorPromocao;
        public decimal ComissaoPorcentagem;
        public decimal ComissaoReal;
        public decimal Pontos;
        public string Imagem;
        public string TipoLista;
        public string TipoPreco;
        public string Linha;
        public string Portaria;
        public DateTime DataVigencia;
        public decimal PrecoAntigo;
        public string RmSaida;
        public string ClassTerapeutica;
        public string UnMedidaSngpc;
        public string UsoProlongado;
        public decimal PrecovendaFarmaciaPopular;
        public decimal MargemFarmaciaPopular;
        public decimal ApresentacaoCx;
        public string CodigoAnp;
        public string DescAnp;
        public string Observacoes;
    }
}
