using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjetoSistema
{
    internal class CadastrarCliente
    {
        public int Codigo;
        public string TipoDocumento;
        public string doc;
        public string InsEstadual;
        public string IndIE;
        public string InsMunicipal;
        public string Nome;
        public int RG;
        public DateTime DataEmissao;
        public string Orgao;
        public string RazaoSocial;
        public string Endereco;
        public string Numero;
        public string Bairro;
        public string CEP;
        public string Referencia;
        public string Apelido;
        public string Email;
        public string Pais;
        public string Estado;
        public string Cidade;
        public decimal LimiteCredito;
        public string Telefone;
        public string Telefone2;
        public string Celular;
        public string Sexo;
        public string EstadoCivil;
        public string Nacionalidade;
        public string UF;
        public string Naturalidade;
        public DateTime DataNascimento;
        public string StatusAtividade;
        public string VenderAPrazo;
        public string Pai;
        public string Mae;
        public string fonePai;
        public string foneMae;
        public string EnderecoFiliacao;
        public string ReferenciaEnderecoFiliacao;
        public string NumeroEnderecoFiliacao;
        public string CEPFiliacao;
        public string BairroFiliacao;
        public string EstadoFiliacao;
        public string CidadeFiliacao;
        public string EnderecoEntrega;
        public string ReferenciaEntrega;
        public string NumeroEndEntrega;
        public string CEPEntrega;
        public string BairroEntrega;
        public string EstadoEntrega;
        public string CidadeEntrega;
        public string Empresa;
        public string FoneEmpresa;
        public string EnderecoEmpresa;
        public string NumeroEndEmpresa;
        public string CEPEndEmpresa;
        public string BairroEndEmpresa;
        public string UFEmpresa;
        public string CidadeEndEmpresa;
        public string CargoEmpresa;
        public decimal Renda;
        public DateTime DataAdmissao;
        public string NomeAvalista;
        public string CPFAvalista;
        public string RGAvalista;
        public DateTime DataNascAvalista;
        public string FoneAvalista;
        public string EndAvalista;
        public string NumeroEndAvalista;
        public string CepAvalista;
        public string BairroAvalista;
        public string UFAvalista;
        public string CidadeAvalista;
        public string EmpresaAvalista;
        public string CargoAvalista;
        public decimal RendaAvalista;
        public DateTime DataAdmissaoAvalista;
        public string Conjugue;
        public string CPFConjugue;
        public string RGConjugue;
        public DateTime DataNascConjugue;
        public string FoneConjugue;
        public string EndConjugue;
        public string NumeroEndConjugue;
        public string CepConjugue;
        public string BairroConjuge;
        public string UFConjugue;
        public string CidadeConjugue;
        public string EmpresaConjugue;
        public string CargoEmpresaConjugue;
        public decimal RendaConjugue;
        public DateTime DataAdmissaoConjugue;
        public string NumeroDoCartaoCliente;
        public string TabelaDePreco;
        public string FotoCliente;
        public string Vendedor;
        public string ReferenciaComercial;
        public string Comercial1;
        public string Comercial2;
        public string Comercial3;
        public string Bancaria1;
        public string Bancaria2;
        public string Observacoes;
    }
}
